### ISSUE TITLE
Migrations are not compatible with Django 1.9

### ISSUE THREAD

**Issue by JurajKavkaAdaptiware** [Alir3z4/cmsplugin-filery#11]
Migrations are not longer compatible with Dj1.9. Thank You for help.

```
Traceback (most recent call last):
  File "/home/juro/work/prog/web/dj/intranetls/.upg/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/juro/work/prog/web/dj/intranetls/.upg/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check_migrations()
  File "/home/juro/work/prog/web/dj/intranetls/.upg/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 163, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/home/juro/work/prog/web/dj/intranetls/.upg/lib/python2.7/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/juro/work/prog/web/dj/intranetls/.upg/lib/python2.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/home/juro/work/prog/web/dj/intranetls/.upg/lib/python2.7/site-packages/django/db/migrations/loader.py", line 170, in build_graph
    self.load_disk()
  File "/home/juro/work/prog/web/dj/intranetls/.upg/lib/python2.7/site-packages/django/db/migrations/loader.py", line 105, in load_disk
    migration_module = import_module("%s.%s" % (module_name, migration_name))
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/juro/work/prog/web/dj/intranetls/.upg/lib/python2.7/site-packages/cmsplugin_filery/migrations/0001_initial.py", line 3, in <module>
    from south.db import db
ImportError: No module named south.db
```

**Comment by advancedtechsoft** [comment]
hi @JurajKavkaAdaptiware i'am facing the same problem after an upgrade 
have you solve it?

**Comment by unabomber87** [comment]
hi @JurajKavkaAdaptiware i'm facing the same problem after an upgrade
have you solve it?

**Comment by JurajKavkaAdaptiware** [comment]
@unabomber87 no i haven't solved it. i simply dropped that plugin from my project. Now, I have my own implementation of gallery based on django photologue with very simle CMS apphook and overriden django templates...

**Comment by Mebus** [comment]
Same problem here...
